server:
  port: 0

springdoc:
  api-docs:
    path: /ms-sucursales/api-docs
  swagger-ui:
    path: /doc/swagger-ui/index.html

spring:
  application:
    name: ms-sucursales
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_cine_sucursales?createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://tu-host-remoto:3306/db_cine_sucursales
    username: root
    password: tu-password-seguro
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none